# =======================================================
# CONFIGURACIÓN DE LA APLICACIÓN SPRING BOOT & MONGODB CLOUD
# =======================================================
spring.application.name=CRUD-clubes-apirest
server.port=${PORT:8888}

# Conexión a MongoDB Cloud Atlas
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://Gabriel_DB:UTS2026@cluster0.wws2n1k.mongodb.net/DB?retryWrites=true&w=majority}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://Gabriel_DB:UTS2026@cluster0.wws2n1k.mongodb.net/DB?retryWrites=true&w=majority}
spring.data.mongodb.database=DB
spring.mongodb.database=DB

# Configuración de Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Configuración de Logging
logging.level.org.springframework.data.mongodb=INFO
logging.level.com.crudclubes_apirest.app=DEBUG
